  <!-- =================================
  @author = Grant McKenzie (gmckenzie@spatialdev.com
  @date = January 2014
  @client = World Bank Open Aid Partnership
  @functionality = Header file (HTML/PHP)
  ====================================== -->

  <header id="appHeader" class="clearfix" style="padding-bottom:5px">
	  <div id="logo" class="left">
		  <a href="index.html"><img src="img/oamLogo.png" alt="Open Aid Partnership" class="lb" /></a>
	  </div>
	  <nav class="header-nav">
		  <ul class="clearfix pt">
			  <li><?php echo strtoupper($dg); ?> <span id="se_h_title">SECTOR ASSIGNOR</span></li>
		  </ul>
	  </nav>
  </header>